version: '3'

volumes: 
  data:
  
services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - /etc/mysql:/var/lib/mysql
    environment:

      - MYSQL_ROOT_PASSWORD=dbaunlocked28
      - MYSQL_DATABASE=graphql_blog


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    links: 
      - db:db

  db_test:
    image: mariadb
    container_name: mariadb_test
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbaunlocked28
      - MYSQL_DATABASE=graphql_blog

  phpmyadmin_test:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_test
    restart: always
    ports:
      - 8082:80
    depends_on:
      - db_test
    links:
      - db_test:db